* The basic outline
Breaking down the patch into a series of levels, and then determining the objects that are in common at each level...

- top-level
  - initializes the "timing"
  - turns on and off "the process"
- second-level
  - contains pitch structures
  - contains the collective probability table(s)
- third-level
  - "audibilizes" the set chosen at level2
    - many little decisions have to be set in motion by the user
  - allows a wave file to be written


Note, development began on a new "pc-set2" section. No progress has been made.

* To get sound
At this stage, a lot of little fussy things have to be set in motion by the user.

* Keeping track of what is actually happening
Is, unfortunately, unreasonably difficult.

* Deeper analysis
The only thing that is clearly happening right now, in fact, is that, at the audio-pc level, Turning on a random transposition "function" sets the wheel in motion for the "change." But this change of transpositional level is really the only that appears to be happening??

There needs to be deeper debugging going on.

Getting every voice (v1-v4) to speak at equal volume, whatever the octave and transposition is not happening.

Once things have moved through the transposition level, there need to be easier ways to control the other sound decisions. These decisions include setting volume, level of reverberation and wave type.
